# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(901, 586)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(217, 227, 218);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 60, 901, 541))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(160, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(160, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(300, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(420, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(660, 40, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(770, 40, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(236, 201, 199);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(540, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(20, 110, 851, 361))
        self.frame_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 821, 321))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.tableWidget.setFont(font)
        self.tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget.setStyleSheet("font: 11pt \"Andale Mono\";\n"
"background-color: rgb(238, 238, 236);")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(150, 10, 281, 16))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(540, 10, 301, 16))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_6.raise_()
        self.label_5.raise_()
        self.tableWidget.raise_()
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(20, 80, 851, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(300, 40, 101, 41))
        self.lineEdit_4.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(420, 40, 101, 41))
        self.lineEdit_5.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(540, 40, 101, 41))
        self.lineEdit_6.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_24.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.comboBox_2.raise_()
        self.label_4.raise_()
        self.label_8.raise_()
        self.frame_2.raise_()
        self.comboBox.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_6.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(660, 40, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(770, 40, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(236, 201, 199);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(540, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(160, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_3.setGeometry(QtCore.QRect(160, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(300, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_4.setGeometry(QtCore.QRect(20, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(420, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_6.setGeometry(QtCore.QRect(540, 40, 111, 41))
        font = QtGui.QFont()
        self.textEdit_6.setFont(font)
        self.textEdit_6.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.textEdit_6.setObjectName("textEdit_6")
        self.frame = QtWidgets.QFrame(self.tab_3)
        self.frame.setGeometry(QtCore.QRect(20, 110, 851, 361))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 30, 521, 321))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet("font: 11pt \"Andale Mono\";\n"
"background-color: rgb(238, 238, 236);")
        self.tableWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_2.setAutoScroll(False)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.tableWidget_2.horizontalHeader().setHighlightSections(True)
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(20, 10, 521, 16))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_88 = QtWidgets.QLabel(self.frame)
        self.label_88.setGeometry(QtCore.QRect(600, 10, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_88.setFont(font)
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setObjectName("label_88")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame)
        self.tableWidget_3.setGeometry(QtCore.QRect(590, 30, 231, 321))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setStyleSheet("font: 11pt \"Andale Mono\";\n"
"background-color: rgb(238, 238, 236);")
        self.tableWidget_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_3.setAutoScroll(False)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        item.setFont(font)
        self.tableWidget_3.setItem(0, 0, item)
        self.label_23.raise_()
        self.label_88.raise_()
        self.tableWidget_2.raise_()
        self.tableWidget_3.raise_()
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 40, 101, 41))
        self.lineEdit_2.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(420, 40, 101, 41))
        self.lineEdit_3.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.comboBox_3.raise_()
        self.label_12.raise_()
        self.comboBox_4.raise_()
        self.label_13.raise_()
        self.frame.raise_()
        self.textEdit_6.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(620, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(320, 10, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(10, 40, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(18)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(78, 154, 6);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(620, 40, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(18)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(204, 0, 0);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(320, 40, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(18)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(1, 72, 138);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 80, 851, 391))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.frame_5 = QtWidgets.QFrame(self.tab_7)
        self.frame_5.setGeometry(QtCore.QRect(20, 10, 311, 161))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 20, 291, 51))
        self.tableWidget_4.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"font: 11pt \"Andale Mono\";")
        self.tableWidget_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_4.setAutoScroll(False)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(2)
        self.tableWidget_4.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_15.setGeometry(QtCore.QRect(180, 110, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_55 = QtWidgets.QLabel(self.frame_5)
        self.label_55.setGeometry(QtCore.QRect(10, 80, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 110, 151, 41))
        self.lineEdit_14.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_55.raise_()
        self.tableWidget_4.raise_()
        self.pushButton_15.raise_()
        self.lineEdit_14.raise_()
        self.frame_6 = QtWidgets.QFrame(self.tab_7)
        self.frame_6.setGeometry(QtCore.QRect(350, 10, 471, 161))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_13.setGeometry(QtCore.QRect(270, 110, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_14.setGeometry(QtCore.QRect(370, 30, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("background-color: rgb(236, 201, 199);")
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_40 = QtWidgets.QLabel(self.frame_6)
        self.label_40.setGeometry(QtCore.QRect(10, 80, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_39 = QtWidgets.QLabel(self.frame_6)
        self.label_39.setGeometry(QtCore.QRect(10, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_9.setGeometry(QtCore.QRect(270, 30, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_38 = QtWidgets.QLabel(self.frame_6)
        self.label_38.setGeometry(QtCore.QRect(140, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_47 = QtWidgets.QLabel(self.frame_6)
        self.label_47.setGeometry(QtCore.QRect(140, 80, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 30, 101, 41))
        self.lineEdit_10.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 110, 101, 41))
        self.lineEdit_11.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_12.setGeometry(QtCore.QRect(130, 30, 121, 41))
        self.lineEdit_12.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_13.setGeometry(QtCore.QRect(130, 110, 121, 41))
        self.lineEdit_13.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_38.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        self.label_40.raise_()
        self.label_39.raise_()
        self.pushButton_9.raise_()
        self.label_47.raise_()
        self.lineEdit_10.raise_()
        self.lineEdit_11.raise_()
        self.lineEdit_12.raise_()
        self.lineEdit_13.raise_()
        self.graphicsView_4 = PlotWidget(self.tab_7)
        self.graphicsView_4.setGeometry(QtCore.QRect(20, 190, 391, 151))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView_5 = PlotWidget(self.tab_7)
        self.graphicsView_5.setGeometry(QtCore.QRect(430, 190, 391, 151))
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_11.setGeometry(QtCore.QRect(250, 50, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_44 = QtWidgets.QLabel(self.tab_8)
        self.label_44.setGeometry(QtCore.QRect(20, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.tab_8)
        self.label_45.setGeometry(QtCore.QRect(150, 20, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.comboBox_11 = QtWidgets.QComboBox(self.tab_8)
        self.comboBox_11.setGeometry(QtCore.QRect(20, 50, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.comboBox_11.setFont(font)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_12.setGeometry(QtCore.QRect(390, 50, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("background-color: rgb(236, 201, 199);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_46 = QtWidgets.QLabel(self.tab_8)
        self.label_46.setGeometry(QtCore.QRect(640, 20, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_50 = QtWidgets.QLabel(self.tab_8)
        self.label_50.setGeometry(QtCore.QRect(540, 20, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.progressBar_2 = QtWidgets.QProgressBar(self.tab_8)
        self.progressBar_2.setGeometry(QtCore.QRect(710, 30, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.progressBar_2.setFont(font)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar = QtWidgets.QProgressBar(self.tab_8)
        self.progressBar.setGeometry(QtCore.QRect(710, 70, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_51 = QtWidgets.QLabel(self.tab_8)
        self.label_51.setGeometry(QtCore.QRect(640, 60, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_53 = QtWidgets.QLabel(self.tab_8)
        self.label_53.setGeometry(QtCore.QRect(710, 0, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_52 = QtWidgets.QLabel(self.tab_8)
        self.label_52.setGeometry(QtCore.QRect(540, 60, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("font: 11pt \"Andale Mono\";")
        self.label_52.setObjectName("label_52")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_15.setGeometry(QtCore.QRect(150, 50, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.graphicsView_2 = PlotWidget(self.tab_8)
        self.graphicsView_2.setGeometry(QtCore.QRect(20, 110, 391, 231))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = PlotWidget(self.tab_8)
        self.graphicsView_3.setGeometry(QtCore.QRect(440, 110, 391, 231))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.pushButton_11.raise_()
        self.label_44.raise_()
        self.label_45.raise_()
        self.comboBox_11.raise_()
        self.pushButton_12.raise_()
        self.progressBar.raise_()
        self.label_51.raise_()
        self.label_53.raise_()
        self.label_52.raise_()
        self.lineEdit_15.raise_()
        self.label_46.raise_()
        self.progressBar_2.raise_()
        self.label_50.raise_()
        self.graphicsView_2.raise_()
        self.graphicsView_3.raise_()
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_16.setGeometry(QtCore.QRect(300, 140, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_57 = QtWidgets.QLabel(self.tab_9)
        self.label_57.setGeometry(QtCore.QRect(20, 140, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_57.setFont(font)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_17.setGeometry(QtCore.QRect(300, 220, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("background-color: rgb(236, 201, 199);")
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_59 = QtWidgets.QLabel(self.tab_9)
        self.label_59.setGeometry(QtCore.QRect(20, 10, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_59.setFont(font)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_18.setGeometry(QtCore.QRect(560, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.pushButton_18.setObjectName("pushButton_18")
        self.textEdit_28 = QtWidgets.QTextEdit(self.tab_9)
        self.textEdit_28.setGeometry(QtCore.QRect(20, 40, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.textEdit_28.setFont(font)
        self.textEdit_28.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.textEdit_28.setObjectName("textEdit_28")
        self.label_61 = QtWidgets.QLabel(self.tab_9)
        self.label_61.setGeometry(QtCore.QRect(380, 10, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_61.setFont(font)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_19.setGeometry(QtCore.QRect(700, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("background-color: rgb(236, 201, 199);")
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_60 = QtWidgets.QLabel(self.tab_9)
        self.label_60.setGeometry(QtCore.QRect(180, 90, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_60.setFont(font)
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.tableWidget_9 = QtWidgets.QTableWidget(self.tab_9)
        self.tableWidget_9.setGeometry(QtCore.QRect(460, 110, 311, 231))
        self.tableWidget_9.setStyleSheet("font: 11pt \"Andale Mono\";\n"
"background-color: rgb(238, 238, 236);")
        self.tableWidget_9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(3)
        self.tableWidget_9.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(2, item)
        self.label_58 = QtWidgets.QLabel(self.tab_9)
        self.label_58.setGeometry(QtCore.QRect(20, 220, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_58.setFont(font)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_7.setGeometry(QtCore.QRect(180, 140, 101, 41))
        self.lineEdit_7.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_8.setGeometry(QtCore.QRect(180, 220, 101, 41))
        self.lineEdit_8.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_9.setGeometry(QtCore.QRect(400, 40, 141, 41))
        self.lineEdit_9.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_89 = QtWidgets.QLabel(self.tab_9)
        self.label_89.setGeometry(QtCore.QRect(20, 300, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_89.setFont(font)
        self.label_89.setAlignment(QtCore.Qt.AlignCenter)
        self.label_89.setObjectName("label_89")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_16.setGeometry(QtCore.QRect(180, 300, 101, 41))
        self.lineEdit_16.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pushButton_29 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_29.setGeometry(QtCore.QRect(300, 300, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.pushButton_29.setFont(font)
        self.pushButton_29.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.pushButton_29.setObjectName("pushButton_29")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 851, 51))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "PIPO"))
        self.comboBox.setItemText(1, _translate("MainWindow", "B"))
        self.comboBox.setItemText(2, _translate("MainWindow", "A"))
        self.comboBox.setItemText(3, _translate("MainWindow", "AA"))
        self.comboBox.setItemText(4, _translate("MainWindow", "AAA"))
        self.comboBox.setItemText(5, _translate("MainWindow", "JUMBO"))
        self.comboBox.setItemText(6, _translate("MainWindow", "BLANCO"))
        self.comboBox.setItemText(7, _translate("MainWindow", "VENCIDO VENTA"))
        self.comboBox.setItemText(8, _translate("MainWindow", "DESTRUIDOS"))
        self.label.setText(_translate("MainWindow", "TIPO "))
        self.label_2.setText(_translate("MainWindow", "GALPON"))
        self.label_3.setText(_translate("MainWindow", "UNIDADES"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "POLLITAS"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "GALLINAS"))
        self.label_4.setText(_translate("MainWindow", "CUBETAS"))
        self.pushButton.setText(_translate("MainWindow", "AGREGAR"))
        self.pushButton_2.setText(_translate("MainWindow", "ELIMINAR"))
        self.label_8.setText(_translate("MainWindow", "SOBRANTES"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "PIPO"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "B"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "A"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "AA"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "AAA"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "JUMBO"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "BLANCO"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "VENCIDO VENTA"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "DESTRUIDOS"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "TOTAL"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "UNIDADES"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CUBETAS"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SOBRANTES"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "UNIDADES"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "CUBETAS"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "SOBRANTES"))
        self.label_5.setText(_translate("MainWindow", "POLLITAS"))
        self.label_6.setText(_translate("MainWindow", "GALLINAS"))
        self.label_24.setText(_translate("MainWindow", "PRODUCCION DEL DIA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "PRODUCCION"))
        self.pushButton_3.setText(_translate("MainWindow", "VENTA"))
        self.pushButton_4.setText(_translate("MainWindow", "DEVOLUCION"))
        self.label_9.setText(_translate("MainWindow", "OBSERVACION"))
        self.label_10.setText(_translate("MainWindow", "PRESENTACION"))
        self.label_11.setText(_translate("MainWindow", "TIPO"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "PIPO"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "B"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "A"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "AA"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "AAA"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "JUMBO"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "BLANCO"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "VENCIDO VENTA"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "DESTRUIDOS"))
        self.label_12.setText(_translate("MainWindow", "CANTIDAD"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "UNIDADES"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "CUBETAS"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "SOBRANTES"))
        self.label_13.setText(_translate("MainWindow", "PRECIO"))
        self.textEdit_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "PIPO"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "B"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "A"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "AA"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "AAA"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "JUMBO"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "BLANCO"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "VENCIDO VENTA"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "DESTRUIDOS"))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "TOTAL"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "UNIDADES"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CUBETAS"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SOBRANTES"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "VENTAS DIA"))
        self.label_23.setText(_translate("MainWindow", "INVENTARIO DE HUEVOS"))
        self.label_88.setText(_translate("MainWindow", "VENTAS ULTIMOS 7 DIAS"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "PIPO"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "B"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "A"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "AA"))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "AAA"))
        item = self.tableWidget_3.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "JUMBO"))
        item = self.tableWidget_3.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "BLANCO"))
        item = self.tableWidget_3.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "VENCIDO VENTA"))
        item = self.tableWidget_3.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "DESTRUIDOS"))
        item = self.tableWidget_3.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "TOTAL"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ACUMULADO"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "VENTAS"))
        self.label_14.setText(_translate("MainWindow", "DINERO DISPONIBLE (EFECTIVO)"))
        self.label_15.setText(_translate("MainWindow", "DEUDA A AGRO CAMPO"))
        self.label_16.setText(_translate("MainWindow", "CUPO DE ENDEUDAMIENTO"))
        self.label_17.setText(_translate("MainWindow", "8\'541.005 PESOS"))
        self.label_18.setText(_translate("MainWindow", "8\'541.005 PESOS"))
        self.label_19.setText(_translate("MainWindow", "8\'541.005 PESOS"))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "DISPONIBLE"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "BULTO"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "COSTALES"))
        self.pushButton_15.setText(_translate("MainWindow", "GASTADOS"))
        self.label_55.setText(_translate("MainWindow", "BULTO DE ALIMENTO"))
        self.pushButton_13.setText(_translate("MainWindow", "VENDER"))
        self.pushButton_14.setText(_translate("MainWindow", "FIAR"))
        self.label_40.setText(_translate("MainWindow", "COSTALES"))
        self.label_39.setText(_translate("MainWindow", "BULTOS"))
        self.pushButton_9.setText(_translate("MainWindow", "COMPRAR"))
        self.label_38.setText(_translate("MainWindow", "PRECIO"))
        self.label_47.setText(_translate("MainWindow", "PRECIO"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "ALIMENTO"))
        self.pushButton_11.setText(_translate("MainWindow", "AGREGAR"))
        self.label_44.setText(_translate("MainWindow", "TIPO ANIMAL"))
        self.label_45.setText(_translate("MainWindow", "CANTIDAD"))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "POLLITA"))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "GALLINA"))
        self.pushButton_12.setText(_translate("MainWindow", "DAR DE BAJA"))
        self.label_46.setText(_translate("MainWindow", "1500"))
        self.label_50.setText(_translate("MainWindow", "POLLITAS :"))
        self.label_51.setText(_translate("MainWindow", "1500"))
        self.label_53.setText(_translate("MainWindow", "RENDIMIENTO"))
        self.label_52.setText(_translate("MainWindow", "GALLINAS : "))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "GALPONES"))
        self.pushButton_16.setText(_translate("MainWindow", "ABONAR"))
        self.label_57.setText(_translate("MainWindow", "ABONO A AGROPAISA"))
        self.pushButton_17.setText(_translate("MainWindow", "RETIRAR"))
        self.label_59.setText(_translate("MainWindow", "MOTIVO"))
        self.pushButton_18.setText(_translate("MainWindow", "GASTADO"))
        self.textEdit_28.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Andale Mono\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\';\"><br /></p></body></html>"))
        self.label_61.setText(_translate("MainWindow", "TOTAL GASTADO"))
        self.pushButton_19.setText(_translate("MainWindow", "FIADO"))
        self.label_60.setText(_translate("MainWindow", "DINERO "))
        item = self.tableWidget_9.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_9.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_9.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_9.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_9.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_9.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_9.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_9.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_9.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "FECHA"))
        item = self.tableWidget_9.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MOTIVO"))
        item = self.tableWidget_9.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CANTIDAD"))
        self.label_58.setText(_translate("MainWindow", "PARA CAJA MAYOR"))
        self.label_89.setText(_translate("MainWindow", "INGRESO CAJA MENOR"))
        self.pushButton_29.setText(_translate("MainWindow", "INGRESAR"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "CAJA MENOR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "GESTION"))
        self.label_7.setText(_translate("MainWindow", "GRANJA VILLAMARIA  FAMILIA LOPEZ SUAREZ"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

