# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
from pyqtgraph import PlotWidget
from PyQt5.QtWidgets import QTableWidgetItem


from manejo_archivos import *
from manejo_huevos import *
from manejo_ventas import *
from manejo_inventario import *
from manejo_galpon import *
from venta_empaques import *
from gasto_alimento import *
from manejo_compras import *
from manejo_credito import *
from manejo_caja_mayor import *
from logic import * 

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(914, 586)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(217, 227, 218);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(0, 60, 901, 541))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.tabs.setFont(font)
        self.tabs.setAutoFillBackground(False)
        self.tabs.setStyleSheet("")
        self.tabs.setObjectName("tabs")
        self.produccion = QtWidgets.QWidget()
        self.produccion.setObjectName("produccion")
        self.tipo_produccion = QtWidgets.QComboBox(self.produccion)
        self.tipo_produccion.setGeometry(QtCore.QRect(160, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.tipo_produccion.setFont(font)
        self.tipo_produccion.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.tipo_produccion.setObjectName("tipo_produccion")
        self.tipo_produccion.addItem("")
        self.tipo_produccion.addItem("")
        self.tipo_produccion.addItem("")
        self.tipo_produccion.addItem("")
        self.tipo_produccion.addItem("")
        self.tipo_produccion.addItem("")
        self.tipo_produccion.addItem("")
        self.tipo_produccion.addItem("")
        self.tipo_produccion.addItem("")
        self.label = QtWidgets.QLabel(self.produccion)
        self.label.setGeometry(QtCore.QRect(160, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.produccion)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.produccion)
        self.label_3.setGeometry(QtCore.QRect(300, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.galpon_produccion = QtWidgets.QComboBox(self.produccion)
        self.galpon_produccion.setGeometry(QtCore.QRect(20, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.galpon_produccion.setFont(font)
        self.galpon_produccion.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.galpon_produccion.setObjectName("galpon_produccion")
        self.galpon_produccion.addItem("")
        self.galpon_produccion.addItem("")
        self.label_4 = QtWidgets.QLabel(self.produccion)
        self.label_4.setGeometry(QtCore.QRect(420, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.boton_agregar_produccion = QtWidgets.QPushButton(self.produccion)
        self.boton_agregar_produccion.setGeometry(QtCore.QRect(660, 40, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.boton_agregar_produccion.setFont(font)
        self.boton_agregar_produccion.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.boton_agregar_produccion.setObjectName("boton_agregar_produccion")
        self.boton_eliminar_produccion = QtWidgets.QPushButton(self.produccion)
        self.boton_eliminar_produccion.setGeometry(QtCore.QRect(770, 40, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.boton_eliminar_produccion.setFont(font)
        self.boton_eliminar_produccion.setStyleSheet("background-color: rgb(236, 201, 199);")
        self.boton_eliminar_produccion.setObjectName("boton_eliminar_produccion")
        self.label_8 = QtWidgets.QLabel(self.produccion)
        self.label_8.setGeometry(QtCore.QRect(540, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.frame_2 = QtWidgets.QFrame(self.produccion)
        self.frame_2.setGeometry(QtCore.QRect(20, 110, 851, 361))
        self.frame_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.tabla_produccion_diaria = QtWidgets.QTableWidget(self.frame_2)
        self.tabla_produccion_diaria.setGeometry(QtCore.QRect(10, 30, 821, 321))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.tabla_produccion_diaria.setFont(font)
        self.tabla_produccion_diaria.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabla_produccion_diaria.setStyleSheet("font: 11pt \"Andale Mono\";\n"
"background-color: rgb(238, 238, 236);")
        self.tabla_produccion_diaria.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabla_produccion_diaria.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabla_produccion_diaria.setAutoScroll(False)
        self.tabla_produccion_diaria.setObjectName("tabla_produccion_diaria")
        self.tabla_produccion_diaria.setColumnCount(7)
        self.tabla_produccion_diaria.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        item.setFont(font)
        self.tabla_produccion_diaria.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_produccion_diaria.setItem(9, 3, item)
        self.titulo_pollitas = QtWidgets.QLabel(self.frame_2)
        self.titulo_pollitas.setGeometry(QtCore.QRect(150, 10, 281, 16))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.titulo_pollitas.setFont(font)
        self.titulo_pollitas.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_pollitas.setObjectName("titulo_pollitas")
        self.titulo_gallinas = QtWidgets.QLabel(self.frame_2)
        self.titulo_gallinas.setGeometry(QtCore.QRect(540, 10, 301, 16))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.titulo_gallinas.setFont(font)
        self.titulo_gallinas.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_gallinas.setObjectName("titulo_gallinas")
        self.titulo_gallinas.raise_()
        self.titulo_pollitas.raise_()
        self.tabla_produccion_diaria.raise_()
        self.label_24 = QtWidgets.QLabel(self.produccion)
        self.label_24.setGeometry(QtCore.QRect(20, 80, 851, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.unidade_produccion = QtWidgets.QLineEdit(self.produccion)
        self.unidade_produccion.setGeometry(QtCore.QRect(300, 40, 101, 41))
        self.unidade_produccion.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.unidade_produccion.setObjectName("unidade_produccion")
        self.cubetas_produccion = QtWidgets.QLineEdit(self.produccion)
        self.cubetas_produccion.setGeometry(QtCore.QRect(420, 40, 101, 41))
        self.cubetas_produccion.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.cubetas_produccion.setObjectName("cubetas_produccion")
        self.sobrantes_produccion = QtWidgets.QLineEdit(self.produccion)
        self.sobrantes_produccion.setGeometry(QtCore.QRect(540, 40, 101, 41))
        self.sobrantes_produccion.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.sobrantes_produccion.setObjectName("sobrantes_produccion")
        self.label_24.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.galpon_produccion.raise_()
        self.label_4.raise_()
        self.label_8.raise_()
        self.frame_2.raise_()
        self.tipo_produccion.raise_()
        self.boton_agregar_produccion.raise_()
        self.boton_eliminar_produccion.raise_()
        self.unidade_produccion.raise_()
        self.cubetas_produccion.raise_()
        self.sobrantes_produccion.raise_()
        self.tabs.addTab(self.produccion, "")
        self.ventas = QtWidgets.QWidget()
        self.ventas.setObjectName("ventas")
        self.boton_venta = QtWidgets.QPushButton(self.ventas)
        self.boton_venta.setGeometry(QtCore.QRect(660, 40, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.boton_venta.setFont(font)
        self.boton_venta.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.boton_venta.setObjectName("boton_venta")
        self.boton_devolucion = QtWidgets.QPushButton(self.ventas)
        self.boton_devolucion.setGeometry(QtCore.QRect(770, 40, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.boton_devolucion.setFont(font)
        self.boton_devolucion.setStyleSheet("background-color: rgb(236, 201, 199);")
        self.boton_devolucion.setObjectName("boton_devolucion")
        self.label_9 = QtWidgets.QLabel(self.ventas)
        self.label_9.setGeometry(QtCore.QRect(540, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.ventas)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.ventas)
        self.label_11.setGeometry(QtCore.QRect(160, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.tipo_venta = QtWidgets.QComboBox(self.ventas)
        self.tipo_venta.setGeometry(QtCore.QRect(160, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.tipo_venta.setFont(font)
        self.tipo_venta.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.tipo_venta.setObjectName("tipo_venta")
        self.tipo_venta.addItem("")
        self.tipo_venta.addItem("")
        self.tipo_venta.addItem("")
        self.tipo_venta.addItem("")
        self.tipo_venta.addItem("")
        self.tipo_venta.addItem("")
        self.tipo_venta.addItem("")
        self.tipo_venta.addItem("")
        self.tipo_venta.addItem("")
        self.label_12 = QtWidgets.QLabel(self.ventas)
        self.label_12.setGeometry(QtCore.QRect(300, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.presentacion_venta = QtWidgets.QComboBox(self.ventas)
        self.presentacion_venta.setGeometry(QtCore.QRect(20, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.presentacion_venta.setFont(font)
        self.presentacion_venta.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.presentacion_venta.setObjectName("presentacion_venta")
        self.presentacion_venta.addItem("")
        self.presentacion_venta.addItem("")
        self.presentacion_venta.addItem("")
        self.label_13 = QtWidgets.QLabel(self.ventas)
        self.label_13.setGeometry(QtCore.QRect(420, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.comentario_venta = QtWidgets.QTextEdit(self.ventas)
        self.comentario_venta.setGeometry(QtCore.QRect(540, 40, 111, 41))
        font = QtGui.QFont()
        self.comentario_venta.setFont(font)
        self.comentario_venta.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.comentario_venta.setObjectName("comentario_venta")
        self.frame = QtWidgets.QFrame(self.ventas)
        self.frame.setGeometry(QtCore.QRect(20, 110, 851, 361))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tabla_inventario = QtWidgets.QTableWidget(self.frame)
        self.tabla_inventario.setGeometry(QtCore.QRect(10, 30, 521, 321))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabla_inventario.setFont(font)
        self.tabla_inventario.setStyleSheet("font: 11pt \"Andale Mono\";\n"
"background-color: rgb(238, 238, 236);")
        self.tabla_inventario.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabla_inventario.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabla_inventario.setAutoScroll(False)
        self.tabla_inventario.setShowGrid(True)
        self.tabla_inventario.setObjectName("tabla_inventario")
        self.tabla_inventario.setColumnCount(4)
        self.tabla_inventario.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario.setHorizontalHeaderItem(3, item)
        self.tabla_inventario.horizontalHeader().setHighlightSections(True)
        self.titulo_inventario = QtWidgets.QLabel(self.frame)
        self.titulo_inventario.setGeometry(QtCore.QRect(20, 10, 521, 16))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.titulo_inventario.setFont(font)
        self.titulo_inventario.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_inventario.setObjectName("titulo_inventario")
        self.titulo_venta_acumulada = QtWidgets.QLabel(self.frame)
        self.titulo_venta_acumulada.setGeometry(QtCore.QRect(600, 10, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.titulo_venta_acumulada.setFont(font)
        self.titulo_venta_acumulada.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_venta_acumulada.setObjectName("titulo_venta_acumulada")
        self.tabla_acumulada = QtWidgets.QTableWidget(self.frame)
        self.tabla_acumulada.setGeometry(QtCore.QRect(590, 30, 231, 321))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabla_acumulada.setFont(font)
        self.tabla_acumulada.setStyleSheet("font: 11pt \"Andale Mono\";\n"
"background-color: rgb(238, 238, 236);")
        self.tabla_acumulada.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabla_acumulada.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabla_acumulada.setAutoScroll(False)
        self.tabla_acumulada.setObjectName("tabla_acumulada")
        self.tabla_acumulada.setColumnCount(1)
        self.tabla_acumulada.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_acumulada.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_acumulada.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_acumulada.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_acumulada.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_acumulada.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_acumulada.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_acumulada.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_acumulada.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_acumulada.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_acumulada.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_acumulada.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        item.setFont(font)
        self.tabla_acumulada.setItem(0, 0, item)
        self.titulo_inventario.raise_()
        self.titulo_venta_acumulada.raise_()
        self.tabla_inventario.raise_()
        self.tabla_acumulada.raise_()
        self.cantidad_venta = QtWidgets.QLineEdit(self.ventas)
        self.cantidad_venta.setGeometry(QtCore.QRect(300, 40, 101, 41))
        self.cantidad_venta.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.cantidad_venta.setObjectName("cantidad_venta")
        self.precio_venta = QtWidgets.QLineEdit(self.ventas)
        self.precio_venta.setGeometry(QtCore.QRect(420, 40, 101, 41))
        self.precio_venta.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.precio_venta.setObjectName("precio_venta")
        self.boton_venta.raise_()
        self.boton_devolucion.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.tipo_venta.raise_()
        self.label_12.raise_()
        self.presentacion_venta.raise_()
        self.label_13.raise_()
        self.frame.raise_()
        self.comentario_venta.raise_()
        self.cantidad_venta.raise_()
        self.precio_venta.raise_()
        self.tabs.addTab(self.ventas, "")
        self.gestion = QtWidgets.QWidget()
        self.gestion.setObjectName("gestion")
        self.label_14 = QtWidgets.QLabel(self.gestion)
        self.label_14.setGeometry(QtCore.QRect(20, 10, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.gestion)
        self.label_15.setGeometry(QtCore.QRect(610, 10, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.cantidad_efectivo = QtWidgets.QLabel(self.gestion)
        self.cantidad_efectivo.setGeometry(QtCore.QRect(20, 40, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(18)
        self.cantidad_efectivo.setFont(font)
        self.cantidad_efectivo.setStyleSheet("color: rgb(78, 154, 6);")
        self.cantidad_efectivo.setAlignment(QtCore.Qt.AlignCenter)
        self.cantidad_efectivo.setObjectName("cantidad_efectivo")
        self.cantidad_deuda = QtWidgets.QLabel(self.gestion)
        self.cantidad_deuda.setGeometry(QtCore.QRect(610, 40, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(18)
        self.cantidad_deuda.setFont(font)
        self.cantidad_deuda.setStyleSheet("color: rgb(204, 0, 0);")
        self.cantidad_deuda.setAlignment(QtCore.Qt.AlignCenter)
        self.cantidad_deuda.setObjectName("cantidad_deuda")
        self.tabs_internas = QtWidgets.QTabWidget(self.gestion)
        self.tabs_internas.setGeometry(QtCore.QRect(10, 80, 851, 391))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.tabs_internas.setFont(font)
        self.tabs_internas.setObjectName("tabs_internas")
        self.teb_alimento = QtWidgets.QWidget()
        self.teb_alimento.setObjectName("teb_alimento")
        self.frame_5 = QtWidgets.QFrame(self.teb_alimento)
        self.frame_5.setGeometry(QtCore.QRect(20, 10, 421, 161))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.tabla_inventario_alimento = QtWidgets.QTableWidget(self.frame_5)
        self.tabla_inventario_alimento.setGeometry(QtCore.QRect(70, 20, 291, 51))
        self.tabla_inventario_alimento.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"font: 11pt \"Andale Mono\";")
        self.tabla_inventario_alimento.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabla_inventario_alimento.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabla_inventario_alimento.setAutoScroll(False)
        self.tabla_inventario_alimento.setObjectName("tabla_inventario_alimento")
        self.tabla_inventario_alimento.setColumnCount(2)
        self.tabla_inventario_alimento.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario_alimento.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario_alimento.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_inventario_alimento.setHorizontalHeaderItem(1, item)
        self.boton_gastar_alimento = QtWidgets.QPushButton(self.frame_5)
        self.boton_gastar_alimento.setGeometry(QtCore.QRect(220, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.boton_gastar_alimento.setFont(font)
        self.boton_gastar_alimento.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.boton_gastar_alimento.setObjectName("boton_gastar_alimento")
        self.label_55 = QtWidgets.QLabel(self.frame_5)
        self.label_55.setGeometry(QtCore.QRect(110, 80, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.cantidad_alimento_dado = QtWidgets.QLineEdit(self.frame_5)
        self.cantidad_alimento_dado.setGeometry(QtCore.QRect(110, 110, 101, 41))
        self.cantidad_alimento_dado.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.cantidad_alimento_dado.setObjectName("cantidad_alimento_dado")
        self.boton_devolver_alimento = QtWidgets.QPushButton(self.frame_5)
        self.boton_devolver_alimento.setGeometry(QtCore.QRect(320, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.boton_devolver_alimento.setFont(font)
        self.boton_devolver_alimento.setStyleSheet("background-color: rgb(236, 201, 199);")
        self.boton_devolver_alimento.setObjectName("boton_devolver_alimento")
        self.galpon_alimentado = QtWidgets.QComboBox(self.frame_5)
        self.galpon_alimentado.setGeometry(QtCore.QRect(10, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.galpon_alimentado.setFont(font)
        self.galpon_alimentado.setObjectName("galpon_alimentado")
        self.galpon_alimentado.addItem("")
        self.galpon_alimentado.addItem("")
        self.label_48 = QtWidgets.QLabel(self.frame_5)
        self.label_48.setGeometry(QtCore.QRect(10, 80, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.label_48.raise_()
        self.label_55.raise_()
        self.tabla_inventario_alimento.raise_()
        self.boton_gastar_alimento.raise_()
        self.cantidad_alimento_dado.raise_()
        self.boton_devolver_alimento.raise_()
        self.galpon_alimentado.raise_()
        self.frame_6 = QtWidgets.QFrame(self.teb_alimento)
        self.frame_6.setGeometry(QtCore.QRect(20, 180, 421, 161))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.vender_costales = QtWidgets.QPushButton(self.frame_6)
        self.vender_costales.setGeometry(QtCore.QRect(220, 110, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.vender_costales.setFont(font)
        self.vender_costales.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.vender_costales.setObjectName("vender_costales")
        self.boton_fiar_costales = QtWidgets.QPushButton(self.frame_6)
        self.boton_fiar_costales.setGeometry(QtCore.QRect(320, 30, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.boton_fiar_costales.setFont(font)
        self.boton_fiar_costales.setStyleSheet("background-color: rgb(236, 201, 199);")
        self.boton_fiar_costales.setObjectName("boton_fiar_costales")
        self.titulo_costales = QtWidgets.QLabel(self.frame_6)
        self.titulo_costales.setGeometry(QtCore.QRect(10, 80, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.titulo_costales.setFont(font)
        self.titulo_costales.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_costales.setObjectName("titulo_costales")
        self.titulo_bultos = QtWidgets.QLabel(self.frame_6)
        self.titulo_bultos.setGeometry(QtCore.QRect(10, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.titulo_bultos.setFont(font)
        self.titulo_bultos.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_bultos.setObjectName("titulo_bultos")
        self.boton_comprar_alimento = QtWidgets.QPushButton(self.frame_6)
        self.boton_comprar_alimento.setGeometry(QtCore.QRect(220, 30, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.boton_comprar_alimento.setFont(font)
        self.boton_comprar_alimento.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.boton_comprar_alimento.setObjectName("boton_comprar_alimento")
        self.titulo_precio = QtWidgets.QLabel(self.frame_6)
        self.titulo_precio.setGeometry(QtCore.QRect(110, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.titulo_precio.setFont(font)
        self.titulo_precio.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_precio.setObjectName("titulo_precio")
        self.titulo_precio_2 = QtWidgets.QLabel(self.frame_6)
        self.titulo_precio_2.setGeometry(QtCore.QRect(110, 80, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.titulo_precio_2.setFont(font)
        self.titulo_precio_2.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_precio_2.setObjectName("titulo_precio_2")
        self.cantidad_bultos_adquirir = QtWidgets.QLineEdit(self.frame_6)
        self.cantidad_bultos_adquirir.setGeometry(QtCore.QRect(10, 30, 91, 41))
        self.cantidad_bultos_adquirir.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.cantidad_bultos_adquirir.setObjectName("cantidad_bultos_adquirir")
        self.Cantidad_costales_vender = QtWidgets.QLineEdit(self.frame_6)
        self.Cantidad_costales_vender.setGeometry(QtCore.QRect(10, 110, 91, 41))
        self.Cantidad_costales_vender.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.Cantidad_costales_vender.setObjectName("Cantidad_costales_vender")
        self.precio_adquisicion_costal = QtWidgets.QLineEdit(self.frame_6)
        self.precio_adquisicion_costal.setGeometry(QtCore.QRect(110, 30, 101, 41))
        self.precio_adquisicion_costal.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.precio_adquisicion_costal.setObjectName("precio_adquisicion_costal")
        self.precio_venta_costal = QtWidgets.QLineEdit(self.frame_6)
        self.precio_venta_costal.setGeometry(QtCore.QRect(110, 110, 101, 41))
        self.precio_venta_costal.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.precio_venta_costal.setObjectName("precio_venta_costal")
        self.titulo_precio_2.raise_()
        self.titulo_precio.raise_()
        self.vender_costales.raise_()
        self.boton_fiar_costales.raise_()
        self.titulo_costales.raise_()
        self.titulo_bultos.raise_()
        self.boton_comprar_alimento.raise_()
        self.cantidad_bultos_adquirir.raise_()
        self.Cantidad_costales_vender.raise_()
        self.precio_adquisicion_costal.raise_()
        self.precio_venta_costal.raise_()
        self.graphicsView_4 = PlotWidget(self.teb_alimento)
        self.graphicsView_4.setGeometry(QtCore.QRect(470, 10, 361, 161))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView_5 = PlotWidget(self.teb_alimento)
        self.graphicsView_5.setGeometry(QtCore.QRect(470, 180, 361, 161))
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.tabs_internas.addTab(self.teb_alimento, "")
        self.tab_galpones = QtWidgets.QWidget()
        self.tab_galpones.setObjectName("tab_galpones")
        self.boton_agregar_animales = QtWidgets.QPushButton(self.tab_galpones)
        self.boton_agregar_animales.setGeometry(QtCore.QRect(250, 50, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.boton_agregar_animales.setFont(font)
        self.boton_agregar_animales.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.boton_agregar_animales.setObjectName("boton_agregar_animales")
        self.label_44 = QtWidgets.QLabel(self.tab_galpones)
        self.label_44.setGeometry(QtCore.QRect(20, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.tab_galpones)
        self.label_45.setGeometry(QtCore.QRect(150, 20, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.galpon_administrar_animales = QtWidgets.QComboBox(self.tab_galpones)
        self.galpon_administrar_animales.setGeometry(QtCore.QRect(20, 50, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.galpon_administrar_animales.setFont(font)
        self.galpon_administrar_animales.setObjectName("galpon_administrar_animales")
        self.galpon_administrar_animales.addItem("")
        self.galpon_administrar_animales.addItem("")
        self.boton_dar_baja_animales = QtWidgets.QPushButton(self.tab_galpones)
        self.boton_dar_baja_animales.setGeometry(QtCore.QRect(390, 50, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.boton_dar_baja_animales.setFont(font)
        self.boton_dar_baja_animales.setStyleSheet("background-color: rgb(236, 201, 199);")
        self.boton_dar_baja_animales.setObjectName("boton_dar_baja_animales")
        self.cantidad_pollitas = QtWidgets.QLabel(self.tab_galpones)
        self.cantidad_pollitas.setGeometry(QtCore.QRect(640, 20, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.cantidad_pollitas.setFont(font)
        self.cantidad_pollitas.setObjectName("cantidad_pollitas")
        self.label_50 = QtWidgets.QLabel(self.tab_galpones)
        self.label_50.setGeometry(QtCore.QRect(540, 20, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.rendimiento_pollitas = QtWidgets.QProgressBar(self.tab_galpones)
        self.rendimiento_pollitas.setGeometry(QtCore.QRect(710, 30, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.rendimiento_pollitas.setFont(font)
        self.rendimiento_pollitas.setProperty("value", 24)
        self.rendimiento_pollitas.setObjectName("rendimiento_pollitas")
        self.rendimiento_gallinas = QtWidgets.QProgressBar(self.tab_galpones)
        self.rendimiento_gallinas.setGeometry(QtCore.QRect(710, 70, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.rendimiento_gallinas.setFont(font)
        self.rendimiento_gallinas.setProperty("value", 24)
        self.rendimiento_gallinas.setObjectName("rendimiento_gallinas")
        self.cantidad_gallinas = QtWidgets.QLabel(self.tab_galpones)
        self.cantidad_gallinas.setGeometry(QtCore.QRect(640, 60, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.cantidad_gallinas.setFont(font)
        self.cantidad_gallinas.setObjectName("cantidad_gallinas")
        self.label_53 = QtWidgets.QLabel(self.tab_galpones)
        self.label_53.setGeometry(QtCore.QRect(710, 0, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_52 = QtWidgets.QLabel(self.tab_galpones)
        self.label_52.setGeometry(QtCore.QRect(540, 60, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("font: 11pt \"Andale Mono\";")
        self.label_52.setObjectName("label_52")
        self.cantidad_animales_editar = QtWidgets.QLineEdit(self.tab_galpones)
        self.cantidad_animales_editar.setGeometry(QtCore.QRect(150, 50, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.cantidad_animales_editar.setFont(font)
        self.cantidad_animales_editar.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.cantidad_animales_editar.setObjectName("cantidad_animales_editar")
        self.graphicsView_2 = PlotWidget(self.tab_galpones)
        self.graphicsView_2.setGeometry(QtCore.QRect(20, 110, 391, 231))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = PlotWidget(self.tab_galpones)
        self.graphicsView_3.setGeometry(QtCore.QRect(440, 110, 391, 231))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.boton_agregar_animales.raise_()
        self.label_44.raise_()
        self.label_45.raise_()
        self.galpon_administrar_animales.raise_()
        self.boton_dar_baja_animales.raise_()
        self.rendimiento_gallinas.raise_()
        self.cantidad_gallinas.raise_()
        self.label_53.raise_()
        self.label_52.raise_()
        self.cantidad_animales_editar.raise_()
        self.cantidad_pollitas.raise_()
        self.rendimiento_pollitas.raise_()
        self.label_50.raise_()
        self.graphicsView_2.raise_()
        self.graphicsView_3.raise_()
        self.tabs_internas.addTab(self.tab_galpones, "")
        self.caja_menor = QtWidgets.QWidget()
        self.caja_menor.setObjectName("caja_menor")
        self.boton_abonar = QtWidgets.QPushButton(self.caja_menor)
        self.boton_abonar.setGeometry(QtCore.QRect(300, 140, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.boton_abonar.setFont(font)
        self.boton_abonar.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.boton_abonar.setObjectName("boton_abonar")
        self.label_57 = QtWidgets.QLabel(self.caja_menor)
        self.label_57.setGeometry(QtCore.QRect(20, 140, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_57.setFont(font)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.boton_retirar = QtWidgets.QPushButton(self.caja_menor)
        self.boton_retirar.setGeometry(QtCore.QRect(300, 220, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.boton_retirar.setFont(font)
        self.boton_retirar.setStyleSheet("background-color: rgb(236, 201, 199);")
        self.boton_retirar.setObjectName("boton_retirar")
        self.label_59 = QtWidgets.QLabel(self.caja_menor)
        self.label_59.setGeometry(QtCore.QRect(20, 10, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_59.setFont(font)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.boton_comprar_caja_menor = QtWidgets.QPushButton(self.caja_menor)
        self.boton_comprar_caja_menor.setGeometry(QtCore.QRect(560, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.boton_comprar_caja_menor.setFont(font)
        self.boton_comprar_caja_menor.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.boton_comprar_caja_menor.setObjectName("boton_comprar_caja_menor")
        self.motivo_gasto = QtWidgets.QTextEdit(self.caja_menor)
        self.motivo_gasto.setGeometry(QtCore.QRect(20, 40, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.motivo_gasto.setFont(font)
        self.motivo_gasto.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.motivo_gasto.setObjectName("motivo_gasto")
        self.label_61 = QtWidgets.QLabel(self.caja_menor)
        self.label_61.setGeometry(QtCore.QRect(400, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_61.setFont(font)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.boton_fiar_caja_menor = QtWidgets.QPushButton(self.caja_menor)
        self.boton_fiar_caja_menor.setGeometry(QtCore.QRect(700, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.boton_fiar_caja_menor.setFont(font)
        self.boton_fiar_caja_menor.setStyleSheet("background-color: rgb(236, 201, 199);")
        self.boton_fiar_caja_menor.setObjectName("boton_fiar_caja_menor")
        self.label_60 = QtWidgets.QLabel(self.caja_menor)
        self.label_60.setGeometry(QtCore.QRect(190, 110, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_60.setFont(font)
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.tableWidget_9 = QtWidgets.QTableWidget(self.caja_menor)
        self.tableWidget_9.setGeometry(QtCore.QRect(460, 110, 311, 231))
        self.tableWidget_9.setStyleSheet("font: 11pt \"Andale Mono\";\n"
"background-color: rgb(238, 238, 236);")
        self.tableWidget_9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(3)
        self.tableWidget_9.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(2, item)
        self.label_58 = QtWidgets.QLabel(self.caja_menor)
        self.label_58.setGeometry(QtCore.QRect(20, 220, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_58.setFont(font)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.abonar_dinero = QtWidgets.QLineEdit(self.caja_menor)
        self.abonar_dinero.setGeometry(QtCore.QRect(190, 140, 91, 41))
        self.abonar_dinero.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.abonar_dinero.setObjectName("abonar_dinero")
        self.retirar_dinero = QtWidgets.QLineEdit(self.caja_menor)
        self.retirar_dinero.setGeometry(QtCore.QRect(190, 220, 91, 41))
        self.retirar_dinero.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.retirar_dinero.setObjectName("retirar_dinero")
        self.cantidad_dinero_caja = QtWidgets.QLineEdit(self.caja_menor)
        self.cantidad_dinero_caja.setGeometry(QtCore.QRect(400, 40, 141, 41))
        self.cantidad_dinero_caja.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.cantidad_dinero_caja.setObjectName("cantidad_dinero_caja")
        self.label_89 = QtWidgets.QLabel(self.caja_menor)
        self.label_89.setGeometry(QtCore.QRect(20, 300, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_89.setFont(font)
        self.label_89.setAlignment(QtCore.Qt.AlignCenter)
        self.label_89.setObjectName("label_89")
        self.ingresar_dinero = QtWidgets.QLineEdit(self.caja_menor)
        self.ingresar_dinero.setGeometry(QtCore.QRect(190, 300, 91, 41))
        self.ingresar_dinero.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.ingresar_dinero.setObjectName("ingresar_dinero")
        self.boton_invertir_caja_menor = QtWidgets.QPushButton(self.caja_menor)
        self.boton_invertir_caja_menor.setGeometry(QtCore.QRect(300, 300, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.boton_invertir_caja_menor.setFont(font)
        self.boton_invertir_caja_menor.setStyleSheet("background-color: rgb(209, 207, 192);")
        self.boton_invertir_caja_menor.setObjectName("boton_invertir_caja_menor")
        self.label_62 = QtWidgets.QLabel(self.caja_menor)
        self.label_62.setGeometry(QtCore.QRect(190, 200, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_62.setFont(font)
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.caja_menor)
        self.label_63.setGeometry(QtCore.QRect(190, 280, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_63.setFont(font)
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.caja_menor)
        self.label_64.setGeometry(QtCore.QRect(460, 80, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_64.setFont(font)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.label_64.raise_()
        self.boton_abonar.raise_()
        self.label_57.raise_()
        self.boton_retirar.raise_()
        self.label_59.raise_()
        self.boton_comprar_caja_menor.raise_()
        self.motivo_gasto.raise_()
        self.label_61.raise_()
        self.boton_fiar_caja_menor.raise_()
        self.label_60.raise_()
        self.tableWidget_9.raise_()
        self.label_58.raise_()
        self.abonar_dinero.raise_()
        self.retirar_dinero.raise_()
        self.cantidad_dinero_caja.raise_()
        self.label_89.raise_()
        self.ingresar_dinero.raise_()
        self.boton_invertir_caja_menor.raise_()
        self.label_62.raise_()
        self.label_63.raise_()
        self.tabs_internas.addTab(self.caja_menor, "")
        self.label_16 = QtWidgets.QLabel(self.gestion)
        self.label_16.setGeometry(QtCore.QRect(310, 11, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.cantidad_cupo = QtWidgets.QLabel(self.gestion)
        self.cantidad_cupo.setGeometry(QtCore.QRect(310, 40, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(18)
        self.cantidad_cupo.setFont(font)
        self.cantidad_cupo.setStyleSheet("color: rgb(1, 72, 138);")
        self.cantidad_cupo.setAlignment(QtCore.Qt.AlignCenter)
        self.cantidad_cupo.setObjectName("cantidad_cupo")
        self.tabs.addTab(self.gestion, "")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 851, 51))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        self.tabs_internas.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema para el control de granja de huevos"))
        self.tipo_produccion.setItemText(0, _translate("MainWindow", "PIPO"))
        self.tipo_produccion.setItemText(1, _translate("MainWindow", "B"))
        self.tipo_produccion.setItemText(2, _translate("MainWindow", "A"))
        self.tipo_produccion.setItemText(3, _translate("MainWindow", "AA"))
        self.tipo_produccion.setItemText(4, _translate("MainWindow", "AAA"))
        self.tipo_produccion.setItemText(5, _translate("MainWindow", "JUMBO"))
        self.tipo_produccion.setItemText(6, _translate("MainWindow", "BLANCO"))
        self.tipo_produccion.setItemText(7, _translate("MainWindow", "VENCIDO VENTA"))
        self.tipo_produccion.setItemText(8, _translate("MainWindow", "DESTRUIDOS"))
        self.label.setText(_translate("MainWindow", "TIPO "))
        self.label_2.setText(_translate("MainWindow", "GALPON"))
        self.label_3.setText(_translate("MainWindow", "UNIDADES"))
        self.galpon_produccion.setItemText(0, _translate("MainWindow", "POLLITAS"))
        self.galpon_produccion.setItemText(1, _translate("MainWindow", "GALLINAS"))
        self.label_4.setText(_translate("MainWindow", "CUBETAS"))
        self.boton_agregar_produccion.setText(_translate("MainWindow", "AGREGAR"))
        self.boton_eliminar_produccion.setText(_translate("MainWindow", "ELIMINAR"))
        self.label_8.setText(_translate("MainWindow", "SOBRANTES"))
        item = self.tabla_produccion_diaria.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "PIPO"))
        item = self.tabla_produccion_diaria.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "B"))
        item = self.tabla_produccion_diaria.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "A"))
        item = self.tabla_produccion_diaria.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "AA"))
        item = self.tabla_produccion_diaria.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "AAA"))
        item = self.tabla_produccion_diaria.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "JUMBO"))
        item = self.tabla_produccion_diaria.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "BLANCO"))
        item = self.tabla_produccion_diaria.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "VENCIDO VENTA"))
        item = self.tabla_produccion_diaria.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "DESTRUIDOS"))
        item = self.tabla_produccion_diaria.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "TOTAL"))
        item = self.tabla_produccion_diaria.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "UNIDADES"))
        item = self.tabla_produccion_diaria.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CUBETAS"))
        item = self.tabla_produccion_diaria.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SOBRANTES"))
        item = self.tabla_produccion_diaria.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "UNIDADES"))
        item = self.tabla_produccion_diaria.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "CUBETAS"))
        item = self.tabla_produccion_diaria.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "SOBRANTES"))
        __sortingEnabled = self.tabla_produccion_diaria.isSortingEnabled()
        self.tabla_produccion_diaria.setSortingEnabled(False)
        item = self.tabla_produccion_diaria.item(0, 3)
        item.setText(_translate("MainWindow", "########"))
        item = self.tabla_produccion_diaria.item(1, 3)
        item.setText(_translate("MainWindow", "########"))
        item = self.tabla_produccion_diaria.item(2, 3)
        item.setText(_translate("MainWindow", "########"))
        item = self.tabla_produccion_diaria.item(3, 3)
        item.setText(_translate("MainWindow", "########"))
        item = self.tabla_produccion_diaria.item(4, 3)
        item.setText(_translate("MainWindow", "########"))
        item = self.tabla_produccion_diaria.item(5, 3)
        item.setText(_translate("MainWindow", "########"))
        item = self.tabla_produccion_diaria.item(6, 3)
        item.setText(_translate("MainWindow", "########"))
        item = self.tabla_produccion_diaria.item(7, 3)
        item.setText(_translate("MainWindow", "########"))
        item = self.tabla_produccion_diaria.item(8, 3)
        item.setText(_translate("MainWindow", "########"))
        item = self.tabla_produccion_diaria.item(9, 3)
        item.setText(_translate("MainWindow", "########"))
        self.tabla_produccion_diaria.setSortingEnabled(__sortingEnabled)
        self.titulo_pollitas.setText(_translate("MainWindow", "POLLITAS"))
        self.titulo_gallinas.setText(_translate("MainWindow", "GALLINAS"))
        self.label_24.setText(_translate("MainWindow", "PRODUCCION DEL DIA"))
        self.tabs.setTabText(self.tabs.indexOf(self.produccion), _translate("MainWindow", "PRODUCCION"))
        self.boton_venta.setText(_translate("MainWindow", "VENTA"))
        self.boton_devolucion.setText(_translate("MainWindow", "DEVOLUCION"))
        self.label_9.setText(_translate("MainWindow", "OBSERVACION"))
        self.label_10.setText(_translate("MainWindow", "PRESENTACION"))
        self.label_11.setText(_translate("MainWindow", "TIPO"))
        self.tipo_venta.setItemText(0, _translate("MainWindow", "PIPO"))
        self.tipo_venta.setItemText(1, _translate("MainWindow", "B"))
        self.tipo_venta.setItemText(2, _translate("MainWindow", "A"))
        self.tipo_venta.setItemText(3, _translate("MainWindow", "AA"))
        self.tipo_venta.setItemText(4, _translate("MainWindow", "AAA"))
        self.tipo_venta.setItemText(5, _translate("MainWindow", "JUMBO"))
        self.tipo_venta.setItemText(6, _translate("MainWindow", "BLANCO"))
        self.tipo_venta.setItemText(7, _translate("MainWindow", "VENCIDO VENTA"))
        self.tipo_venta.setItemText(8, _translate("MainWindow", "DESTRUIDOS"))
        self.label_12.setText(_translate("MainWindow", "CANTIDAD"))
        self.presentacion_venta.setItemText(0, _translate("MainWindow", "UNIDADES"))
        self.presentacion_venta.setItemText(1, _translate("MainWindow", "CUBETAS"))
        self.presentacion_venta.setItemText(2, _translate("MainWindow", "SOBRANTES"))
        self.label_13.setText(_translate("MainWindow", "PRECIO"))
        self.comentario_venta.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        item = self.tabla_inventario.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "PIPO"))
        item = self.tabla_inventario.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "B"))
        item = self.tabla_inventario.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "A"))
        item = self.tabla_inventario.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "AA"))
        item = self.tabla_inventario.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "AAA"))
        item = self.tabla_inventario.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "JUMBO"))
        item = self.tabla_inventario.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "BLANCO"))
        item = self.tabla_inventario.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "VENCIDO VENTA"))
        item = self.tabla_inventario.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "DESTRUIDOS"))
        item = self.tabla_inventario.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "TOTAL"))
        item = self.tabla_inventario.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "UNIDADES"))
        item = self.tabla_inventario.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CUBETAS"))
        item = self.tabla_inventario.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SOBRANTES"))
        item = self.tabla_inventario.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "VENTAS DIA"))
        self.titulo_inventario.setText(_translate("MainWindow", "INVENTARIO DE HUEVOS"))
        self.titulo_venta_acumulada.setText(_translate("MainWindow", "VENTAS ACUMULADAS"))
        item = self.tabla_acumulada.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "PIPO"))
        item = self.tabla_acumulada.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "B"))
        item = self.tabla_acumulada.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "A"))
        item = self.tabla_acumulada.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "AA"))
        item = self.tabla_acumulada.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "AAA"))
        item = self.tabla_acumulada.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "JUMBO"))
        item = self.tabla_acumulada.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "BLANCO"))
        item = self.tabla_acumulada.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "VENCIDO VENTA"))
        item = self.tabla_acumulada.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "DESTRUIDOS"))
        item = self.tabla_acumulada.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "TOTAL"))
        item = self.tabla_acumulada.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ACUMULADO"))
        __sortingEnabled = self.tabla_acumulada.isSortingEnabled()
        self.tabla_acumulada.setSortingEnabled(False)
        self.tabla_acumulada.setSortingEnabled(__sortingEnabled)
        self.tabs.setTabText(self.tabs.indexOf(self.ventas), _translate("MainWindow", "VENTAS"))
        self.label_14.setText(_translate("MainWindow", "DINERO DISPONIBLE (EFECTIVO)"))
        self.label_15.setText(_translate("MainWindow", "DEUDA A AGRO PAISA "))
        self.cantidad_efectivo.setText(_translate("MainWindow", "8\'541.005 PESOS"))
        self.cantidad_deuda.setText(_translate("MainWindow", "8\'541.005 PESOS"))
        item = self.tabla_inventario_alimento.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "DISPONIBLE"))
        item = self.tabla_inventario_alimento.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "BULTO"))
        item = self.tabla_inventario_alimento.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "EMPAQUES"))
        self.boton_gastar_alimento.setText(_translate("MainWindow", "GASTADOS"))
        self.label_55.setText(_translate("MainWindow", "BULTOS"))
        self.boton_devolver_alimento.setText(_translate("MainWindow", "DEVOLVER"))
        self.galpon_alimentado.setItemText(0, _translate("MainWindow", "POLLITA"))
        self.galpon_alimentado.setItemText(1, _translate("MainWindow", "GALLINA"))
        self.label_48.setText(_translate("MainWindow", "GALPON"))
        self.vender_costales.setText(_translate("MainWindow", "VENDER"))
        self.boton_fiar_costales.setText(_translate("MainWindow", "FIAR"))
        self.titulo_costales.setText(_translate("MainWindow", "COSTALES"))
        self.titulo_bultos.setText(_translate("MainWindow", "BULTOS"))
        self.boton_comprar_alimento.setText(_translate("MainWindow", "COMPRAR"))
        self.titulo_precio.setText(_translate("MainWindow", "PRECIO"))
        self.titulo_precio_2.setText(_translate("MainWindow", "PRECIO"))
        self.tabs_internas.setTabText(self.tabs_internas.indexOf(self.teb_alimento), _translate("MainWindow", "ALIMENTO"))
        self.boton_agregar_animales.setText(_translate("MainWindow", "AGREGAR"))
        self.label_44.setText(_translate("MainWindow", "TIPO ANIMAL"))
        self.label_45.setText(_translate("MainWindow", "CANTIDAD"))
        self.galpon_administrar_animales.setItemText(0, _translate("MainWindow", "POLLITA"))
        self.galpon_administrar_animales.setItemText(1, _translate("MainWindow", "GALLINA"))
        self.boton_dar_baja_animales.setText(_translate("MainWindow", "DAR DE BAJA"))
        self.cantidad_pollitas.setText(_translate("MainWindow", "1500"))
        self.label_50.setText(_translate("MainWindow", "POLLITAS :"))
        self.cantidad_gallinas.setText(_translate("MainWindow", "1500"))
        self.label_53.setText(_translate("MainWindow", "RENDIMIENTO"))
        self.label_52.setText(_translate("MainWindow", "GALLINAS : "))
        self.tabs_internas.setTabText(self.tabs_internas.indexOf(self.tab_galpones), _translate("MainWindow", "GALPONES"))
        self.boton_abonar.setText(_translate("MainWindow", "ABONAR"))
        self.label_57.setText(_translate("MainWindow", "ABONO A AGROPAISA"))
        self.boton_retirar.setText(_translate("MainWindow", "RETIRAR"))
        self.label_59.setText(_translate("MainWindow", "MOTIVO"))
        self.boton_comprar_caja_menor.setText(_translate("MainWindow", "GASTADO"))
        self.motivo_gasto.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Andale Mono\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\';\"><br /></p></body></html>"))
        self.label_61.setText(_translate("MainWindow", "TOTAL GASTADO"))
        self.boton_fiar_caja_menor.setText(_translate("MainWindow", "FIADO"))
        self.label_60.setText(_translate("MainWindow", "DINERO "))
        item = self.tableWidget_9.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_9.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_9.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_9.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_9.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_9.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_9.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_9.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_9.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "FECHA"))
        item = self.tableWidget_9.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MOTIVO"))
        item = self.tableWidget_9.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CANTIDAD"))
        self.label_58.setText(_translate("MainWindow", "PARA CAJA MAYOR"))
        self.label_89.setText(_translate("MainWindow", "INGRESO CAJA MENOR"))
        self.boton_invertir_caja_menor.setText(_translate("MainWindow", "INGRESAR"))
        self.label_62.setText(_translate("MainWindow", "DINERO "))
        self.label_63.setText(_translate("MainWindow", "DINERO "))
        self.label_64.setText(_translate("MainWindow", "ULTIMAS TRANSACCIONES"))
        self.tabs_internas.setTabText(self.tabs_internas.indexOf(self.caja_menor), _translate("MainWindow", "CAJA MENOR"))
        self.label_16.setText(_translate("MainWindow", "CUPO DE ENDEUDAMIENTO"))
        self.cantidad_cupo.setText(_translate("MainWindow", "8\'541.005 PESOS"))
        self.tabs.setTabText(self.tabs.indexOf(self.gestion), _translate("MainWindow", "GESTION"))
        self.label_7.setText(_translate("MainWindow", "GRANJA VILLAMARIA  FAMILIA LOPEZ SUAREZ"))


        self.boton_agregar_produccion.clicked.connect(self.agregar_produccion)
        self.boton_eliminar_produccion.clicked.connect(self.eliminar_produccion)
        self.boton_venta.clicked.connect(self.agregar_venta_gui)
        self.boton_devolucion.clicked.connect(self.eliminar_venta_gui)
        self.boton_agregar_animales.clicked.connect(self.agregar_animales_gui)
        self.boton_dar_baja_animales.clicked.connect(self.eliminar_animales_gui)
        self.boton_gastar_alimento.clicked.connect(self.gastar_alimento)
        self.boton_devolver_alimento.clicked.connect(self.devolver_alimento)
        self.boton_comprar_alimento.clicked.connect(self.comprar_alimento)
        self.boton_fiar_costales.clicked.connect(self.fiar_alimento)
        self.vender_costales.clicked.connect(self.vender_costales_gui)
        self.boton_abonar.clicked.connect(self.abonar_agropaisa)
        self.boton_retirar.clicked.connect(self.retiro_caja)
        self.boton_invertir_caja_menor.clicked.connect(self.ingresaar_saldo_caja)
    def actualizar_inventario(self):
        produccion_gallinas = inventario()
        ventas = venta_acumulada_dia()
        venta_acumulada_total = venta_acumulada()
        for j,huevo in enumerate(tipos_huevo):
                produccion_tipo = produccion_gallinas[produccion_gallinas['tipo']==huevo]
                venta = ventas[ventas['tipo'] == huevo]
                acumulada = venta_acumulada_total[venta_acumulada_total['tipo'] == huevo]
                cubeta= str(int(produccion_tipo['cubeta']))
                unidades=str(int(produccion_tipo['unidades']))
                sobrantes=str(int(produccion_tipo['sobrantes']))
                venta=str(int(venta['precio']))
                acum = str(int(acumulada['precio']))


                item_unidades = QTableWidgetItem()
                item_unidades.setText(unidades)
                self.tabla_inventario.setItem(j,0,item_unidades)
                
                item_cubeta = QTableWidgetItem()
                item_cubeta.setText(cubeta)
                self.tabla_inventario.setItem(j,1,item_cubeta)
                
                item_sobrantes = QTableWidgetItem()
                item_sobrantes.setText(sobrantes)
                self.tabla_inventario.setItem(j,2,item_sobrantes)
                
                item_venta = QTableWidgetItem()
                item_venta.setText(venta)
                self.tabla_inventario.setItem(j,3,item_venta)
        
                item_acum = QTableWidgetItem()
                item_acum.setText(acum)
                self.tabla_acumulada.setItem(j,0,item_acum)
        
#-------------------------------------------------------------------------------

    def actualizar_produccion(self):
        data_produccion = obtener_produccion_diaria()

        tipos_huevo = ['PIPO','B','A','AA','AAA','JUMBO','BLANCO','VENCIDO_VENTA','DESTRUIDOS']

        produccion_gallinas = data_produccion[data_produccion['galpon'] == 'POLLITA']
        for j,huevo in enumerate(tipos_huevo):
                produccion_tipo = produccion_gallinas[produccion_gallinas['tipo']==huevo]
                cubeta= str(int(produccion_tipo['cubeta']))
                unidades=str(int(produccion_tipo['unidades']))
                sobrantes=str(int(produccion_tipo['sobrantes']))
                item_cubeta = QTableWidgetItem()
                item_cubeta.setText(cubeta)
                self.tabla_produccion_diaria.setItem(j,1,item_cubeta)
                
                item_unidades = QTableWidgetItem()
                item_unidades.setText(unidades)
                self.tabla_produccion_diaria.setItem(j,0,item_unidades)
                
                item_sobrantes = QTableWidgetItem()
                item_sobrantes.setText(sobrantes)
                self.tabla_produccion_diaria.setItem(j,2,item_sobrantes)

                self.tabla_acumulada.item(1,3).setText('something')
                         
        produccion_gallinas = data_produccion[data_produccion['galpon'] == 'GALLINA']
        for j,huevo in enumerate(tipos_huevo):
                produccion_tipo = produccion_gallinas[produccion_gallinas['tipo']==huevo]
                cubeta= str(int(produccion_tipo['cubeta']))
                unidades=str(int(produccion_tipo['unidades']))
                sobrantes=str(int(produccion_tipo['sobrantes']))
                item_cubeta = QTableWidgetItem()
                item_cubeta.setText(cubeta)
                self.tabla_produccion_diaria.setItem(j,5,item_cubeta)
                
                item_unidades = QTableWidgetItem()
                item_unidades.setText(unidades)
                self.tabla_produccion_diaria.setItem(j,4,item_unidades)
                
                item_sobrantes = QTableWidgetItem()
                item_sobrantes.setText(sobrantes)
                self.tabla_produccion_diaria.setItem(j,6,item_sobrantes)
        

#-------------------------------------------------------------------------------
    def agregar_produccion(self):
        UNIDADES = self.unidade_produccion.text()
        CUBETAS = self.cubetas_produccion.text()    
        SOBRANTES = self.sobrantes_produccion.text()
        galpon = self.galpon_produccion.currentText()
        huevo  = self.tipo_produccion.currentText()
        
        galpon =  1 if(galpon == 'GALLINAS') else 0
        
        tipos_huevo = ['PIPO','B','A','AA','AAA','JUMBO','BLANCO',
                        'VENCIDO VENTA','DESTRUIDOS']
        
        huevo = tipos_huevo.index(huevo)
        
        if(validar_numeros(UNIDADES,CUBETAS,SOBRANTES)):
                self.unidade_produccion.clear()
                self.cubetas_produccion.clear()
                self.sobrantes_produccion.clear()
                agregar_huevos(galpon,huevo,UNIDADES,CUBETAS,SOBRANTES)
        
        self.actualizar_produccion()


#-------------------------------------------------------------------------------
    
    def eliminar_produccion(self):

        UNIDADES = self.unidade_produccion.text()
        CUBETAS = self.cubetas_produccion.text()    
        SOBRANTES = self.sobrantes_produccion.text()
        galpon = self.galpon_produccion.currentText()
        huevo  = self.tipo_produccion.currentText()
        
        galpon =  1 if(galpon == 'GALLINAS') else 0
        
        tipos_huevo = ['PIPO','B','A','AA','AAA','JUMBO','BLANCO',
                        'VENCIDO VENTA','DESTRUIDOS']
        
        huevo = tipos_huevo.index(huevo)
        
        if(validar_numeros(UNIDADES,CUBETAS,SOBRANTES)):
                self.unidade_produccion.clear()
                self.cubetas_produccion.clear()
                self.sobrantes_produccion.clear()
                agregar_huevos(galpon,huevo,'-'+UNIDADES,'-'+CUBETAS,'-'+SOBRANTES)

        self.actualizar_produccion()

    def actualizar_cantidad_gallinas(self):
            pollitas,gallinas= obtener_animales()
            ren_pollitas,ren_gallinas = obtener_rendimiento_diario()
            self.cantidad_pollitas.setText(str(pollitas))
            self.cantidad_gallinas.setText(str(gallinas))
            self.rendimiento_pollitas.setValue(ren_gallinas)
            self.rendimiento_gallinas.setValue(ren_pollitas)

    def devolver_alimento(self):
        galpon = self.galpon_alimentado.currentText()  
        cantidad = self.cantidad_alimento_dado.text()
        if(validar_numeros(cantidad)):
                self.cantidad_alimento_dado.clear()
                consumo_de_alimento(galpon,'-'+cantidad)

    def actualizar_alimento(self):
        bultos = obtener_cantidad_bultos()
        costales = cantidad_de_empaques()
        
        item_bultos = QTableWidgetItem()
        item_bultos.setText(str(bultos))
        self.tabla_inventario_alimento.setItem(0,0,item_bultos)
        
        item_empaques = QTableWidgetItem()
        item_empaques.setText(str(costales))
        self.tabla_inventario_alimento.setItem(0,1,item_empaques)
                            
    def comprar_alimento(self):
        cantidad = self.cantidad_bultos_adquirir.text()
        precio = self.precio_adquisicion_costal.text()
        if(validar_numeros(cantidad)):
                self.cantidad_bultos_adquirir.clear()
                self.precio_adquisicion_costal.clear()
                ingresar_compra_alimento(cantidad,precio)
        self.actualizar_alimento()
        self.actualizar_saldos()


    def fiar_alimento(self):
        cantidad = self.cantidad_bultos_adquirir.text()
        precio = self.precio_adquisicion_costal.text()
        if(validar_numeros(cantidad)):
                self.cantidad_bultos_adquirir.clear()
                self.precio_adquisicion_costal.clear()
                ingresar_fiado_alimento(cantidad,precio)
        self.actualizar_alimento()

    def vender_costales_gui(self):
        cantidad = self.Cantidad_costales_vender.text()
        precio = self.precio_venta_costal.text()
        if(validar_numeros(cantidad,precio)):
                self.Cantidad_costales_vender.clear()
                self.precio_venta_costal.clear()
                venta_empaques(cantidad,precio)
        self.actualizar_alimento()
        self.actualizar_saldos()

    def ingresaar_saldo_caja(self):
        cantidad = self.ingresar_dinero.text()
        if(validar_numeros(cantidad)):
                self.ingresar_dinero.clear()
                ingreso_caja(cantidad)
        self.actualizar_saldos()

    def abonar_agropaisa(self):
        cantidad = self.abonar_dinero.text()
        if(validar_numeros(cantidad)):
                self.abonar_dinero.clear()
                abono_agropaisa(cantidad)
        self.actualizar_saldos()


    def retiro_caja(self):
        cantidad = self.retirar_dinero.text()
        if(validar_numeros(cantidad)):
                self.retirar_dinero.clear()
                retiro_caja(cantidad)
        self.actualizar_saldos()


    def actualizar_saldos(self):
        deudas = obtener_total_credito()
        saldo = 15000000-deudas
        self.cantidad_deuda.setText(str(deudas)+' PESOS')
        self.cantidad_cupo.setText(str(saldo)+' PESOS')

    def gastar_alimento(self):
        galpon = self.galpon_alimentado.currentText()  
        cantidad = self.cantidad_alimento_dado.text()
        if(validar_numeros(cantidad)):
                self.cantidad_alimento_dado.clear()
                consumo_de_alimento(galpon,cantidad)
        self.actualizar_alimento()


#-------------------------------------------------------------------------------
    def agregar_animales_gui(self):
        galpon = self.galpon_administrar_animales.currentText()
        cantidad = self.cantidad_animales_editar.text()
        if(validar_numeros(cantidad)):
                self.cantidad_animales_editar.clear()
                if(galpon == 'POLLITA'):
                        agregar_animales(str(cantidad),'0')
                elif(galpon == 'GALLINA'):
                        agregar_animales('0',str(cantidad))
        self.actualizar_cantidad_gallinas()

    def eliminar_animales_gui(self):
        galpon = self.galpon_administrar_animales.currentText()
        cantidad = self.cantidad_animales_editar.text()
        if(validar_numeros(cantidad)):
                self.cantidad_animales_editar.clear()
                if(galpon == 'POLLITA'):
                        agregar_animales('-'+str(cantidad),'0')
                elif(galpon == 'GALLINA'):
                        agregar_animales('0','-'+str(cantidad))
        self.actualizar_cantidad_gallinas()

#-------------------------------------------------------------------------------
    def agregar_venta_gui(self):
        cantidad = self.cantidad_venta.text()
        precio = self.precio_venta.text()
        observaciones = self.comentario_venta.toPlainText()
        presentacion = self.presentacion_venta.currentText()
        tipo = self.tipo_venta.currentText()

        presentaciones = ['UNIDADES','CUBETAS','SOBRANTES']

        tipos_huevo = ['PIPO','B','A','AA','AAA','JUMBO','BLANCO',
                        'VENCIDO VENTA','DESTRUIDOS']
        
        presentacion = presentaciones.index(presentacion)
        huevo = tipos_huevo.index(tipo)

        if(validar_numeros(cantidad,precio)):
                self.cantidad_venta.clear()
                self.precio_venta.clear()
                self.comentario_venta.clear()
                if(presentacion == 0):
                        agregar_venta(huevo,cantidad,'0','0',precio,observaciones)
                elif(presentacion == 1):
                        agregar_venta(huevo,'0',cantidad,'0',precio,observaciones)
                elif(presentacion == 2):
                        agregar_venta(huevo,'0','0',cantidad,precio,observaciones)
        
        self.actualizar_inventario()
#-------------------------------------------------------------------------------
    def eliminar_venta_gui(self):
        cantidad = self.cantidad_venta.text()
        precio = self.precio_venta.text()
        observaciones = self.comentario_venta.toPlainText()
        presentacion = self.presentacion_venta.currentText()
        tipo = self.tipo_venta.currentText()

        presentaciones = ['UNIDADES','CUBETAS','SOBRANTES']

        tipos_huevo = ['PIPO','B','A','AA','AAA','JUMBO','BLANCO',
                        'VENCIDO VENTA','DESTRUIDOS']
        
        presentacion = presentaciones.index(presentacion)
        huevo = tipos_huevo.index(tipo)

        if(validar_numeros(cantidad,precio)):
                self.cantidad_venta.clear()
                self.precio_venta.clear()
                self.comentario_venta.clear()
                if(presentacion == 0):
                        agregar_venta(huevo,'-'+ cantidad,'0','0','-'+precio,observaciones)
                elif(presentacion == 1):
                        agregar_venta(huevo,'0','-'+cantidad,'0','-'+precio,observaciones)
                elif(presentacion == 2):
                        agregar_venta(huevo,'0','0','-'+cantidad,'-'+precio,observaciones)
        self.actualizar_inventario()
#-------------------------------------------------------------------------------
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


